[package]
name = "dxml_rs"
license = "MIT OR Apache-2.0"
version = "0.1.0"
authors = ["Dragon987 <dragolekovic@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
